/**
 * DISCLAIMER: THIS IS NOT HOW WE SHOULD STORE A JWT CONSTANT, IT NEEDS TO BE STORED IN A .env or CONFIG file
 * THIS IS ONLY FOR DEMO USE
 */
export const jwtConstants = {
    secret: 'KDSJHLSKDJGHFLKSDJHFLSKDJHGKLDHJKDSKGKLDBNGKLJSJBDGLKSJBDGLKJSDBGLKJDGH',
};